spring.application.name: multi-module-template.api
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml # ?? ??? logging.yml? ????
      - db-core.yml
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: staging

---
spring.config.activate.on-profile: live
